# Azure Container Apps deployment configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-content-analyzer
  labels:
    app: web-content-analyzer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-content-analyzer
  template:
    metadata:
      labels:
        app: web-content-analyzer
    spec:
      containers:
      - name: web-content-analyzer
        image: your-registry/web-content-analyzer:latest
        ports:
        - containerPort: 8000
        env:
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: azure-openai-secrets
              key: endpoint
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: azure-openai-secrets
              key: api-key
        - name: AZURE_OPENAI_DEPLOYMENT_NAME
          value: "gpt-4o"
        - name: ENV
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: web-content-analyzer-service
spec:
  selector:
    app: web-content-analyzer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer